#!/usr/bin/env bash

grunt bump:patch build
git add .

# Modify the last commit
git commit --amend

# Grab the last tag name (the version) and reassign it to the amended commit
LAST_TAG=$(git describe $(git rev-list --tags --max-count=1))
git tag -d $LAST_TAG
git tag $LAST_TAG
git push
git push --tags
